// Generated by gencpp from file sad/ImageSrv.msg
// DO NOT EDIT!


#ifndef SAD_MESSAGE_IMAGESRV_H
#define SAD_MESSAGE_IMAGESRV_H

#include <ros/service_traits.h>


#include <sad/ImageSrvRequest.h>
#include <sad/ImageSrvResponse.h>


namespace sad
{

struct ImageSrv
{

typedef ImageSrvRequest Request;
typedef ImageSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ImageSrv
} // namespace sad


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sad::ImageSrv > {
  static const char* value()
  {
    return "ba55116f263d40ea8759822097ad63d4";
  }

  static const char* value(const ::sad::ImageSrv&) { return value(); }
};

template<>
struct DataType< ::sad::ImageSrv > {
  static const char* value()
  {
    return "sad/ImageSrv";
  }

  static const char* value(const ::sad::ImageSrv&) { return value(); }
};


// service_traits::MD5Sum< ::sad::ImageSrvRequest> should match
// service_traits::MD5Sum< ::sad::ImageSrv >
template<>
struct MD5Sum< ::sad::ImageSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sad::ImageSrv >::value();
  }
  static const char* value(const ::sad::ImageSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sad::ImageSrvRequest> should match
// service_traits::DataType< ::sad::ImageSrv >
template<>
struct DataType< ::sad::ImageSrvRequest>
{
  static const char* value()
  {
    return DataType< ::sad::ImageSrv >::value();
  }
  static const char* value(const ::sad::ImageSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sad::ImageSrvResponse> should match
// service_traits::MD5Sum< ::sad::ImageSrv >
template<>
struct MD5Sum< ::sad::ImageSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sad::ImageSrv >::value();
  }
  static const char* value(const ::sad::ImageSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sad::ImageSrvResponse> should match
// service_traits::DataType< ::sad::ImageSrv >
template<>
struct DataType< ::sad::ImageSrvResponse>
{
  static const char* value()
  {
    return DataType< ::sad::ImageSrv >::value();
  }
  static const char* value(const ::sad::ImageSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SAD_MESSAGE_IMAGESRV_H
