// Generated by gencpp from file encoder/TimeDist.msg
// DO NOT EDIT!


#ifndef ENCODER_MESSAGE_TIMEDIST_H
#define ENCODER_MESSAGE_TIMEDIST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace encoder
{
template <class ContainerAllocator>
struct TimeDist_
{
  typedef TimeDist_<ContainerAllocator> Type;

  TimeDist_()
    : timestamp()
    , distanceLeft(0.0)
    , distanceRight(0.0)  {
    }
  TimeDist_(const ContainerAllocator& _alloc)
    : timestamp()
    , distanceLeft(0.0)
    , distanceRight(0.0)  {
  (void)_alloc;
    }



   typedef ros::Time _timestamp_type;
  _timestamp_type timestamp;

   typedef double _distanceLeft_type;
  _distanceLeft_type distanceLeft;

   typedef double _distanceRight_type;
  _distanceRight_type distanceRight;





  typedef boost::shared_ptr< ::encoder::TimeDist_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::encoder::TimeDist_<ContainerAllocator> const> ConstPtr;

}; // struct TimeDist_

typedef ::encoder::TimeDist_<std::allocator<void> > TimeDist;

typedef boost::shared_ptr< ::encoder::TimeDist > TimeDistPtr;
typedef boost::shared_ptr< ::encoder::TimeDist const> TimeDistConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::encoder::TimeDist_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::encoder::TimeDist_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::encoder::TimeDist_<ContainerAllocator1> & lhs, const ::encoder::TimeDist_<ContainerAllocator2> & rhs)
{
  return lhs.timestamp == rhs.timestamp &&
    lhs.distanceLeft == rhs.distanceLeft &&
    lhs.distanceRight == rhs.distanceRight;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::encoder::TimeDist_<ContainerAllocator1> & lhs, const ::encoder::TimeDist_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace encoder

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::encoder::TimeDist_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::encoder::TimeDist_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::encoder::TimeDist_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::encoder::TimeDist_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::encoder::TimeDist_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::encoder::TimeDist_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::encoder::TimeDist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a8d79d031810f535ef4e5c20861539b";
  }

  static const char* value(const ::encoder::TimeDist_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a8d79d031810f53ULL;
  static const uint64_t static_value2 = 0x5ef4e5c20861539bULL;
};

template<class ContainerAllocator>
struct DataType< ::encoder::TimeDist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "encoder/TimeDist";
  }

  static const char* value(const ::encoder::TimeDist_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::encoder::TimeDist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# TimeDist.msg\n"
"time timestamp\n"
"float64 distanceLeft\n"
"float64 distanceRight\n"
;
  }

  static const char* value(const ::encoder::TimeDist_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::encoder::TimeDist_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.distanceLeft);
      stream.next(m.distanceRight);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TimeDist_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::encoder::TimeDist_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::encoder::TimeDist_<ContainerAllocator>& v)
  {
    s << indent << "timestamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.timestamp);
    s << indent << "distanceLeft: ";
    Printer<double>::stream(s, indent + "  ", v.distanceLeft);
    s << indent << "distanceRight: ";
    Printer<double>::stream(s, indent + "  ", v.distanceRight);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ENCODER_MESSAGE_TIMEDIST_H
